MooiWallBundle:
    resource: "@MooiWallBundle/Resources/config/routing.yml"
    prefix:   /

MooiUserBundle:
    resource: "@MooiUserBundle/Resources/config/routing.yml"
    prefix:   /user

MooiUserBundle_UserLogin:
    pattern:  /login
    defaults: { _controller: MooiUserBundle:User:login }

index:
    pattern:  /
    defaults: { _controller: MooiUserBundle:User:index }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

login:
    pattern:   /login

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
