security:
    acl:
        connection: default
    encoders:
        Mooi\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_STUDENT:    ROLE_USER
        ROLE_TEACHER:    ROLE_STUDENT
        ROLE_ADMIN:      ROLE_TEACHER
        ROLE_SUPERADMIN: ROLE_ADMIN

    providers:
        user_db:
            entity: { class: MooiUserBundle:User, property: username }

    firewalls:
        user_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/create, roles: ROLE_TEACHER }
        - { path: ^/teacher, roles: ROLE_TEACHER }
        - { path: ^/, roles: ROLE_STUDENT }