Mooi\WallBundle\Entity\Image:
    type: entity
    table: images
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 60
        time:
            type: datetime
        url:
          type: string
          length: 100
    manyToOne:
        posts:
            targetEntity: Mooi\WallBundle\Entity\Post
            inversedBy: posts
            joinColumn:
                name: post_id
                referencedColumnName: id
                