Mooi\WallBundle\Entity\Image:
    type: entity
    table: images
    lifecycleCallbacks:
        prePersist:  [ preUpload ]
        preUpdate:   [ preUpload ]
        postPersist: [ upload ]
        postUpdate:  [ upload ]
        preRemove:   [ storeFilenameForRemove ]
        postRemove:  [ removeUpload ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            nullable: true
            type: string
            length: 255
        time:
            type: datetime
        extension:
            type: string
            length: 4