Mooi\WallBundle\Entity\Notification:
  type: entity
  table: notifications
  repositoryClass: Mooi\WallBundle\Repository\NotificationRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    message:
      type: string
      length: 255
    quote:
      type: string
      length: 53
      nullable: true
    new:
      type: boolean
    time:
      type: datetime
  manyToOne:
    owner:
      targetEntity: Mooi\UserBundle\Entity\User
      inversedBy: notifications
      joinColumn:
        name: owner_id
        referencedColumnName: id
    about:
      targetEntity: Mooi\UserBundle\Entity\User
      inversedBy: notifications_about
      joinColumn:
        name: about_id
        referencedColumnName: id
    post:
      targetEntity: Mooi\WallBundle\Entity\Post
      joinColumn:
        name: post_id
        referencedColumnName: id