Mooi\WallBundle\Entity\Post:
    type: entity
    table: posts
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        sender_id:
            type: integer
            length: 9
        text:
            type: string
            length: 60
        time:
            type: date
    oneToMany:
        users:
            targetEntity: Mooi\UserBundle\Entity\User
            mappedBy: id
        
           
