Mooi\WallBundle\Entity\Post:
    type: entity
    table: posts
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        text:
            type: string
            length: 60
        time:
            type: datetime
    oneToMany:
        images:
            targetEntity: Image
            mappedBy: post_images
        replies:
            targetEntity: Reply
            mappedBy: posts
    manyToOne:
        sender:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: sender_id
                referencedColumnName: id
        wall_owner:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: wall_owner_id
                referencedColumnName: id
        subject:
            targetEntity: Subject
            inversedBy: posts
            joinColumn:
                name: subject_id
                referencedColumnName: id    