Mooi\WallBundle\Entity\Post:
    type: entity
    table: posts
    repositoryClass: Mooi\WallBundle\Repository\PostRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        likes:
            type: integer
            length: 4
        text:
            type: string
        type:
            type: string
            columnDefinition: ENUM('post', 'reply')
        time:
            type: datetime
    manyToMany:
        replies:
            targetEntity: Mooi\WallBundle\Entity\Post
            cascade: ["persist"]
            inversedBy: mainPosts
            orderBy: 
                time: DESC
            joinTable:
                name: posts_has_posts
                joinColumns:
                    joinColumn:
                        name: post_id
                        referencedColumnName: id
                inverseJoinColumns:
                    joinColumn:
                        name: reply_id
                        referencedColumnName: id
        mainPosts:
            targetEntity: Mooi\WallBundle\Entity\Post
            mappedBy: replies
            cascade: ["persist"]
    oneToMany:
        images:
            targetEntity: Image
            mappedBy: post_images
        notifications:
            targetEntity: Mooi\WallBundle\Entity\Notification
            mappedBy: post
    manyToOne:
        sender:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: sender_id
                referencedColumnName: id
        wall_owner:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: wall_owner_id
                referencedColumnName: id
        subject:
            targetEntity: Subject
            inversedBy: posts
            joinColumn:
                name: subject_id
                referencedColumnName: id
                onDelete: cascade