Mooi\WallBundle\Entity\Post:
    type: entity
    table: posts
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        likes:
            type: integer
            length: 4
        text:
            type: string
            length: 60
        time:
            type: datetime
    manyToMany:
        replies:
            targetEntity: Mooi\WallBundle\Entity\Post
            inversedBy: mainPosts
            orderBy: 
                time: DESC
            joinTable:
                name: posts_has_posts
                joinColumns:
                    joinColumn:
                        name: post_id
                        referencedColumnName: id
                inverseJoinColumns:
                    joinColumn:
                        name: reply_id
                        referencedColumnName: id
        mainPosts:
            targetEntity: Mooi\WallBundle\Entity\Post
            mappedBy: replies
    oneToMany:
        images:
            targetEntity: Image
            mappedBy: post_images
    manyToOne:
        sender:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: sender_id
                referencedColumnName: id
        wall_owner:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: wall_owner_id
                referencedColumnName: id
        subject:
            targetEntity: Subject
            inversedBy: posts
            joinColumn:
                name: subject_id
                referencedColumnName: id