Mooi\WallBundle\Entity\Post_has_subject:
    type: entity
    table: posts_has_subjects
    manyToOne:
        subject:
            targetEntity: Subject
            cascade: [persist]
            inversedBy: posts
            joinColumn:
                name: subjects_id
                referencedColumnName: id
        post:
            targetEntity: Post
            cascade: [persist]
            inversedBy: subjects
            joinColumn:
                name: posts_id
                referencedColumnName: id
           
