Mooi\WallBundle\Entity\Post:
    type: entity
    table: posts
    repositoryClass: Mooi\WallBundle\Repository\PostRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        likes:
            type: integer
            length: 4
        text:
            type: string
        type:
            type: string
            columnDefinition: ENUM('post', 'reply')
        time:
            type: datetime
    manyToMany:
        replies:
            targetEntity: Mooi\WallBundle\Entity\Post
            cascade: ["persist"]
            inversedBy: mainPosts
            orderBy: 
                time: ASC
            joinTable:
                name: post_has_replies
                joinColumns:
                    joinColumn:
                        name: post_id
                        referencedColumnName: id
                        onDelete: cascade
                inverseJoinColumns:
                    joinColumn:
                        name: reply_id
                        referencedColumnName: id
        mainPosts:
            targetEntity: Mooi\WallBundle\Entity\Post
            mappedBy: replies
            onDelete: cascade
        images:
            targetEntity: Mooi\WallBundle\Entity\Image
            inversedBy: mainPosts
            orderBy: 
                time: ASC
            joinTable:
                name: post_has_images
                joinColumns:
                    joinColumn:
                        name: post_id
                        referencedColumnName: id
                        onDelete: cascade
                inverseJoinColumns:
                    joinColumn:
                        name: image_id
                        referencedColumnName: id
    oneToMany:
        notifications:
            targetEntity: Mooi\WallBundle\Entity\Notification
            mappedBy: post
    manyToOne:
        sender:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: sender_id_posts
            joinColumn:
                name: sender_id
                referencedColumnName: id
        wall_owner:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: wall_owner_posts
            joinColumn:
                name: wall_owner_id
                referencedColumnName: id
        subject:
            targetEntity: Subject
            inversedBy: posts
            joinColumn:
                name: subject_id
                referencedColumnName: id
                onDelete: cascade