Mooi\WallBundle\Entity\Post:
    type: entity
    table: posts
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        text:
            type: string
            length: 60
        time:
            type: datetime
    manyToMany:
        subjects:
            targetEntity: Subject
            inversedBy: posts
    manyToOne:
        user:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: sender_id
                referencedColumnName: id
        user:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: wall_owner_id
                referencedColumnName: id
