Mooi\WallBundle\Entity\Post:
    type: entity
    table: posts
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        text:
            type: string
            length: 60
        time:
            type: datetime
    oneToMany:
        users:
            targetEntity: Mooi\UserBundle\Entity\User
            mappedBy: user
    manyToMany:
        subjects:
            targetEntity: Subject
            inversedBy: posts
           
