Mooi\WallBundle\Entity\Reply:
    type: entity
    table: replies
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        text:
            type: string
            length: 60
        time:
            type: datetime
    manyToOne:
        post:
            targetEntity: Post
            inversedBy: replies
            joinColumn:
                name: post_id
                referencedColumnName: id
                