Mooi\WallBundle\Entity\Subject:
    type: entity
    table: subjects
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 60
        description:
            type: text
            nullable: true
    oneToMany:
        posts:
            targetEntity: Post
            mappedBy: posts
