MooiWallBundle_WallIndex:
    pattern:  /wall
    defaults: { _controller: MooiWallBundle:Wall:index }
MooiWallBundle_WallCreate:
    pattern: /create
    defaults: { _controller: MooiWallBundle:User:create }

