MooiWallBundle_WallIndex:
    pattern:  /wall/{id}
    defaults: { _controller: MooiWallBundle:Wall:index }
MooiWallBundle_WallEdit:
    pattern: /edit
    defaults: { _controller: MooiWallBundle:Wall:edit }
MooiWallBundle_WallDelete:
    pattern: /delete
    defaults: { _controller: MooiWallBundle:Wall:delete }

