#wall itself
MooiWallBundle_WallIndex:
    pattern:  /wall/{id}
    defaults: { _controller: MooiWallBundle:Wall:index }
    
MooiWallBundle_WallEdit:
    pattern: /wall/edit/{postId}
    defaults: { _controller: MooiWallBundle:Wall:edit }

MooiWallBundle_WallAdd:
    pattern: /wall/add/{id}
    defaults: { _controller: MooiWallBundle:Wall:add }
    
MooiWallBundle_WallDelete:
    pattern: /wall/delete/{postId}
    defaults: { _controller: MooiWallBundle:Wall:delete }

MooiWallBundle_WallLike:
    pattern: /wall/like/{postId}
    defaults: { _controller: MooiWallBundle:Wall:like }
#subjects
MooiWallBundle_SubjectIndex:
    pattern: /subject
    defaults: { _controller: MooiWallBundle:Subject:index }
    
MooiWallBundle_SubjectAdd:
    pattern: /subject/add
    defaults: { _controller: MooiWallBundle:Subject:add }
    
MooiWallBundle_SubjectEdit:
    pattern: /subject/edit/{name}
    defaults: { _controller: MooiWallBundle:Subject:edit }
    
MooiWallBundle_SubjectDelete:
    pattern: /subject/delete/{name}
    defaults: { _controller: MooiWallBundle:Subject:delete }   
#replies
MooiWallBundle_WallReplyAdd:
    pattern: /wall/comment/add/{postId}
    defaults: { _controller: MooiWallBundle:Reply:add }
    
#Notifications
MooiWallBundle_NotificationOverview:
    pattern: /notifications
    defaults: { _controller: MooiWallBundle:Notification:overview }