#wall itself
MooiWallBundle_WallIndex:
    pattern:  /wall/{name}
    defaults: { _controller: MooiWallBundle:Wall:index, name: null }
    
MooiWallBundle_WallEdit:
    pattern: /wall/edit/{postId}
    defaults: { _controller: MooiWallBundle:Wall:edit }

MooiWallBundle_WallAdd:
    pattern: /wall/{name}/add
    defaults: { _controller: MooiWallBundle:Wall:add, name: null }
    
MooiWallBundle_WallDelete:
    pattern: /wall/delete/{postId}
    defaults: { _controller: MooiWallBundle:Wall:delete }

MooiWallBundle_WallLike:
    pattern: /wall/like/{postId}
    defaults: { _controller: MooiWallBundle:Wall:like }

MooiWallBundle_WallFilter:  
    pattern: wall/{name}/filter
    defaults: { _controller: MooiWallBundle:Wall:filter, name: null}
#subjects
MooiWallBundle_SubjectIndex:
    pattern: /subject
    defaults: { _controller: MooiWallBundle:Subject:index }
    
MooiWallBundle_SubjectAdd:
    pattern: /subject/add
    defaults: { _controller: MooiWallBundle:Subject:add }
    
MooiWallBundle_SubjectEdit:
    pattern: /subject/edit/{name}
    defaults: { _controller: MooiWallBundle:Subject:edit }
    
MooiWallBundle_SubjectDelete:
    pattern: /subject/delete/{name}
    defaults: { _controller: MooiWallBundle:Subject:delete }   

#replies
MooiWallBundle_WallReplyAdd:
    pattern: /wall/comment/add/{postId}
    defaults: { _controller: MooiWallBundle:Reply:add }
    
MooiWallBundle_WallReplyEdit:
    pattern: /wall/comment/edit/{replyId}
    defaults: { _controller: MooiWallBundle:Reply:edit }
    
MooiWallBundle_WallReplyDelete:
    pattern: /wall/comment/delete/{replyId}
    defaults: { _controller: MooiWallBundle:Reply:delete }

MooiWallBundle_WallReplyLike:
    pattern: /wall/comment/like/{replyId}
    defaults: { _controller: MooiWallBundle:Reply:like }
    
#Notifications
MooiWallBundle_NotificationOverview:
    pattern: /notifications
    defaults: { _controller: MooiWallBundle:Notification:overview }
    
MooiWallBundle_NotificationMarkAsRead:
    pattern: /notifications/mark
    defaults: { _controller: MooiWallBundle:Notification:markAsRead }
#file upload
MooiWallBundle_WallFileUpload:
    pattern: /wall/file/upload
    defaults: { _controller: MooiWallBundle:File:upload }