#user
MooiUserBundle_UserCreate:
    pattern: /user/create
    defaults: { _controller: MooiUserBundle:User:create }
    
MooiUserBundle_UserEdit:
    pattern: /user/edit/{username}
    defaults: { _controller: MooiUserBundle:User:edit, username: null }
    
MooiUserBundle_ChangeStyle:
    pattern: /user/style
    defaults: { _controller: MooiUserBundle:User:changeStyle}
    
#teacher
MooiUserBundle_TeacherOverview:
    pattern: /teacher
    defaults: { _controller: MooiUserBundle:Teacher:overview }
    
MooiUserBundle_TeacherStudentOverview:
    pattern: /teacher/students
    defaults: { _controller: MooiUserBundle:Teacher:studentOverview }
    
MooiUserBundle_TeacherAddStudentOverview:
    pattern: /teacher/students/add/{username}
    defaults: { _controller: MooiUserBundle:Teacher:addStudent }
    
MooiUserBundle_TeacherRemoveStudentOverview:
    pattern: /teacher/students/remove/{username}
    defaults: { _controller: MooiUserBundle:Teacher:removeStudent }