parameters:
#    mooi_user.example.class: Mooi\UserBundle\Example

services:
#    mooi_user.example:
#        class: %mooi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
