Mooi\UserBundle\Entity\User:
  constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: {fields: username, message: "Er is al een account met deze gebruikersnaam."}
  properties:
    username:
      - NotBlank: {message: "Vul een gebruikersnaam in.", groups: [registration]}
      - MinLength: {limit: 3, message: "Gebruikersnaam moet langer zijn dan 2 tekens.", groups: [registration]}
    first_name:
      - NotBlank: {message: "Vul een voornaam in."}
      - MinLength: {limit: 3, message: "Voornaam moet langer zijn dan 2 tekens."}
    last_name:
      - NotBlank: {message: "Vul een achternaam in."}
      - MinLength: {limit: 3, message: "Achternaam moet langer zijn dan 2 tekens."}
    gender:
      - Choice:
          choices: [man, vrouw]
          message: "Kien een geslacht."
    role:
      - NotBlank: {message: "Selecteer een rol."}
    password:
      - Regex:
          pattern:  "/^.{1,5}$/"
          message:  "Wachtwoord moet 6 tekens of langer zijn."
          match:    false
          groups:   [update]
      - NotBlank: {message: "Vul een wachtwoord in.", groups: [registration]}
      - MinLength: {limit: 6, message: "Wachtwoord moet 6 tekens of langer zijn.", groups: [registration]}
