Mooi\UserBundle\Entity\User:
  constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: {fields: email, message: "Er is al een account met dit emailadress"}
  getters: 
    Username:
      - NotBlank: {message: "Vul een emailadres of studentnummer in."}
      - MinLength: {limit: 3, message: "Emailadress of studentnummer moet langer zijn dan 2 tekens"}
  properties:
    first_name:
      - NotBlank: {message: "Vul een voornaam in."}
      - MinLength: {limit: 3, message: "Voornaam moet langer zijn dan 2 tekens"}
    last_name:
      - NotBlank: {message: "Vul een achternaam in."}
      - MinLength: {limit: 3, message: "Achternaam moet langer zijn dan 2 tekens"}
    role:
      - NotBlank: {message: "Selecteer een rol."}
    email:
      - NotBlank: {message: "Vul een emailadres in."}
      - Email: {message: "Dit emailadres is niet geldig.", checkMX: true}
    password:
      - Regex:
          pattern:  "/^.{1,7}$/"
          message:  "Wachtwoord moet 8 tekens of langer zijn regex"
          match:    false
          groups:   [update]
      - NotBlank: {message: "Vul een wachtwoord in.", groups: [registration]}
      - MinLength: {limit: 8, message: "Wachtwoord moet 8 tekens of langer zijn", groups: [registration]}
