Mooi\UserBundle\Entity\Role:
    type: entity
    table: roles
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 60
    oneToMany:
        users:
            targetEntity: User
            mappedBy: role
