Mooi\UserBundle\Entity\Role:
    type: entity
    table: roles
    repositoryClass: Mooi\UserBundle\Repository\RoleRepository
    Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: internal_name
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 60
        internal_name:
            type: string
            length: 60
            unique: true
    oneToMany:
        users:
            targetEntity: User
            mappedBy: role
            orderBy: 
                first_name: ASC
                last_name: ASC
