Mooi\UserBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        first_name:
            type: string
            length: 60
        last_name:
            type: string
            length: 60
        preposition:
            type: string
            length: 20
        email:
            type: string
            length: 150
        password:
            type: string
            length: 60
    manyToOne:
        role:
            targetEntity: Role
            inversedBy: users
            joinColumn:
                name: role_id
                referencedColumnName: id
