Mooi\UserBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        salt:
            type: string
            length: 32
        username:
            type: string
            length: 150
        first_name:
            type: string
            length: 150
        last_name:
            type: string
            length: 150
        preposition:
            type: string
            length: 20
            nullable: true
        gender:
            type: string
            columnDefinition: ENUM('man', 'vrouw')
        email:
            type: string
            length: 150
            nullable: true
        password:
            type: string
            length: 100
        is_active:
            type: boolean
        date:
            type: datetime
    manyToOne:
        role:
            targetEntity: Role
            inversedBy: users
            joinColumn:
                name: role_id
                referencedColumnName: id
    oneToMany:
        wall_owner_posts:
            targetEntity: Mooi\WallBundle\Entity\Post
            mappedBy: wall_owner
            orderBy: 
                time: DESC
        sender_id_posts:
            targetEntity: Mooi\WallBundle\Entity\Post
            mappedBy: sender
            orderBy: 
                time: DESC
    manyToMany:
        students:
            targetEntity: Mooi\UserBundle\Entity\User
            inversedBy: teachers
            orderBy: 
                first_name: ASC
                last_name: ASC
            joinTable:
                name: teachers_students
                joinColumns:
                    joinColumn:
                        name: teacher_id
                        referencedColumnName: id
                inverseJoinColumns:
                    joinColumn:
                        name: student_id
                        referencedColumnName: id
        teachers:
            targetEntity: Mooi\UserBundle\Entity\User
            mappedBy: students