<?php

namespace Mooi\WallBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Mooi\WallBundle\Entity\Notification;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    
    public function markAsRead($userId)
    {
        
        $entityManager = $this->getEntityManager();
        
        $query = $entityManager->createQueryBuilder()
                ->update('MooiWallBundle:Notification', 'n')
                ->set('n.new', 0)
                ->where('n.owner = :userId')
                ->setParameter('userId', $userId)
                ->getQuery();
                
        $query->execute();
        
    }
    
}