<?php

namespace Mooi\WallBundle\Repository;

use Mooi\WallBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    

    public function findMainPostsByUser($userId)
    {
        
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        
        $queryBuilder->select('p, u')
                ->from('MooiWallBundle:Post', 'p')
                ->innerJoin('p.wall_owner_id', 'u.id')
                ->where('u.id = :user_id')
                ->andWhere('p.type = :type')
                ->orderBy('p.time', 'DESC')
                ->setParameter('user_id', $userId)
                ->setParameter('type', 'post');
        
        return $queryBuilder->getQuery()->getResult();
        
    }
    
}

?>
