<?php

namespace Mooi\WallBundle\Repository;

use Mooi\WallBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    
    
    public function filterYearsPosts()
    {
        
        $query = $this->getEntityManager()
                ->createQuery('SELECT p.time
                                FROM MooiWallBundle:Post p 
                                ORDER BY p.time');
        
        return $query->getResult();
        
    }
    
    public function findMainPostsByUser($userName)
    {

        $query = $this->getEntityManager()
                ->createQuery('SELECT p, u 
                                FROM MooiWallBundle:Post p 
                                JOIN p.wall_owner u
                                WHERE u.username = :user_name
                                AND p.type = :post_type
                                ORDER BY p.time desc')
                                ->setParameter('user_name', $userName)
                                ->setParameter('post_type', 'post');
        
        return $query->getResult();
        
    }
    
}

?>
