<?php

namespace Mooi\WallBundle\Repository;

use Mooi\WallBundle\Entity\Subject;
use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends EntityRepository
{
    
    
    public function filterByYearAndSubject($userName, $subject, $year)
    {
        
        $query = $this->getEntityManager()
                ->createQuery('SELECT s, p, u
                                FROM MooiWallBundle:Subject s
                                JOIN s.posts p
                                JOIN p.wall_owner u
                                WHERE s.id = :post_subject_id
                                AND u.username = :user_name
                                AND SUBSTRING(p.time, 1, 4) = SUBSTRING(:year, 1, 4)')
                                ->setParameter('post_subject_id', $subject)
                                ->setParameter('user_name', $userName)
                                ->setParameter('year', $year);
        return $query->getResult();
        
    }
    
    public function getAllSubjectsByName()
    {
        
        $query = $this->getEntityManager()
                ->createQuery('SELECT s.name
                                FROM MooiWallBundle:Subject s');
        return $query->getResult();
        
    }
    
}

?>
