<?php

namespace Mooi\WallBundle\Repository;

use Mooi\WallBundle\Entity\Subject;
use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends EntityRepository
{
    
    
    public function filterByYearAndSubject($userName, $subject, $year)
    {
        
        $query = $this->getEntityManager()
                ->createQuery('SELECT s, p
                                FROM MooiWallBundle:Subject s
                                JOIN s.posts p
                                WHERE s.id = :post_subject_id
                                ')//AND YEAR(p.time) = 2006
                                ->setParameter('post_subject_id', $subject);
        return $query->getResult();
        /*
                                'SELECT p, u 
                                FROM MooiWallBundle:Post p 
                                JOIN p.wall_owner u
                                WHERE u.username = :user_name
                                AND p.type = :post_type
                                AND p.subject = :post_subject
                                ORDER BY p.time desc')
                                ->setParameter('user_name', $userName)
                                ->setParameter('post_type', 'post' 
         
         */
    }
    
}

?>
